substitutions:
  _ENV: gs://h-07-450914_cloudbuild/source/.env

steps:
  # Step 1: Ambil file .env dari Cloud Storage
  - name: "gcr.io/cloud-builders/gsutil"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "Mengambil file .env dari Cloud Storage..."
        mkdir -p /workspace/secrets
        gsutil cp "$_ENV" /workspace/secrets/.env
        echo "File .env berhasil disimpan di /workspace/secrets/.env"

  # Step 2: Build image dari folder backend
  - name: "gcr.io/cloud-builders/docker"
    dir: "backend"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/tcc-be", "."]

  # Step 3: Push image ke registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/tcc-be"]

  # Step 4: Deploy ke Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run", "deploy", "be",
        "--image", "gcr.io/$PROJECT_ID/tcc-be",
        "--timeout", "1000s",
        "--port", "5000",
        "--region", "us-central1",
        "--allow-unauthenticated"
      ]

options:
  logging: CLOUD_LOGGING_ONLY
timeout: "1600s"
