steps:
  - name: 'node'
    dir: 'frontend'
    entrypoint: 'npm'
    args: ['install']

  - name: 'node'
    dir: 'frontend'
    entrypoint: 'npm'
    args: ['run', 'build']

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    dir: "frontend"
    entrypoint: "bash"
    args:
      [
        "-c",
        "gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy"
      ]

options:
  logging: CLOUD_LOGGING_ONLY

timeout: "1600s"
